import {templates,capabilityCatalog,skillCatalog,newCandidate,validateStep,candidateFingerprint,trialIsCurrent} from './hiring-store.mjs';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names=['Position','Identity','Capabilities & Skills','Access & Authority','Trial Work','Founder Confirm'];
export const lobbyURL=(id='',welcome=false)=>`/employees?demo=1&companyPreview=1${id?`&${welcome?'welcome':'focus'}=${encodeURIComponent(id)}`:''}`;
export function createHiringUI({store,onHired,onRefresh}) {
  let c=null,busy=false,generation=0,trialOutcome='PASS';
  const dialog=document.createElement('dialog');dialog.id='hire-wizard';dialog.setAttribute('aria-labelledby','hire-title');document.body.append(dialog);
  const tags=values=>`<div class="hire-tags">${values.map(v=>`<span>${esc(v)}</span>`).join('')||'<small>尚未选择</small>'}</div>`;
  const field=(key,label,area=false)=>`<label class="hire-field">${label}${area?`<textarea name="${key}" maxlength="${key==='about'?500:1500}">${esc(c[key])}</textarea>`:`<input name="${key}" value="${esc(c[key])}" maxlength="${key==='name'?40:100}">`}</label>`;
  const picker=(key,values)=>`<div class="hire-options">${[...new Set([...values,...c[key]])].map(v=>`<label><input type="checkbox" name="${key}" value="${esc(v)}" ${c[key].includes(v)?'checked':''}><span>${esc(v)}</span></label>`).join('')}</div>`;
  const card=()=>`<aside class="hire-id-card"><span class="eyebrow">YOUR NEXT TEAMMATE</span><img src="/employee/assets/portrait-${c.portrait}.png" alt="候选员工像素肖像"><h3 data-preview-name>${esc(c.name||'Your new teammate')}</h3><p>${esc(c.position)}</p>${tags(c.capabilities.slice(0,4))}<span class="badge draft">Ready for Trial · 候选人</span></aside>`;
  function overview(){return `<div class="hire-overview"><div class="section-head"><div><span class="eyebrow">PEOPLE MAKE POSSIBILITY</span><h2>Build the team your company needs.</h2></div><button class="primary-button" data-hire-new="engineer">＋ Hire Employee</button></div><p class="section-note">从公司需要的能力出发，认识你的下一位伙伴。<span class="badge draft">Prototype / Demo</span></p><section class="hire-need"><div><span class="eyebrow">CAPABILITY NEEDS · 示例需求</span><h3>Your company needs</h3><strong class="hire-need-tag">payments.integration</strong><p>支付集成需要一位新的伙伴。这是能力缺口的演示示例。</p></div><button class="secondary-button" data-hire-need>Hire for this need →</button></section><section class="hire-home-section"><h3>Position Templates <small>从熟悉的岗位开始</small></h3><div class="hire-template-grid">${templates.map((t,i)=>`<button data-hire-new="${t.id}" class="hire-template"><span class="hire-template-icon">${['⌘','◈','✓','↗','☏','✎'][i]}</span><strong>${t.title}</strong><small>${t.label}</small><span>＋</span></button>`).join('')}</div></section><div class="hire-overview-columns"><section class="hire-home-section"><h3>Open Positions <small>${store.drafts.length} 个本地草稿</small></h3>${store.drafts.length?store.drafts.map(d=>`<button class="hire-list-row" data-hire-resume="${d.id}"><span class="hire-template-icon">◇</span><span><strong>${esc(d.position||'未命名岗位')}</strong><small>${d.capabilities.length} capabilities · ${names[d.step-1]} · 尚未入职</small></span><span>→</span></button>`).join(''):'<div class="hire-empty">为下一阶段留一个位置。<small>定义岗位后，草稿会保存在这里。</small></div>'}</section><section class="hire-home-section"><h3>Recent Hires <small>演示团队</small></h3>${store.hires.length?store.hires.slice().reverse().slice(0,6).map(h=>`<a class="hire-list-row" href="${lobbyURL(h.employeeId)}"><img src="/employee/assets/portrait-${h.candidate.portrait}.png" alt=""><span><strong>${esc(h.candidate.name)}</strong><small>${esc(h.candidate.position)}</small></span><span class="badge">Available</span></a>`).join(''):'<div class="hire-empty">每个好团队，都从一次相识开始。<small>完成试用并确认后，新员工将出现在圆桌大厅。</small></div>'}</section></div><p class="section-note">${store.persistent?'草稿与入职记录仅保存在此浏览器。':'浏览器存储不可用，记录仅保留在本页；跨页同步不可用。'}试用、能力证据与权限均为演示。</p></div>`;}
  function save(){c=store.save(c);onRefresh();}
  function error(message){const el=dialog.querySelector('[role="alert"]');if(el)el.textContent=message;}
  function close(){generation++;busy=false;dialog.close();onRefresh();}
  function open(template='engineer',need='',draft){c=draft?structuredClone(draft):newCandidate(template,need);trialOutcome=c.trial?.verdict??'PASS';if(c.step===6&&!trialIsCurrent(c))c.step=5;try{save();render();dialog.showModal();}catch(e){onRefresh();alert(e.message);}}
  function body(){
    if(c.step===1)return `<h2>What does your company need?</h2><p class="hire-muted">先明确岗位与使命，再认识加入这个岗位的员工。</p>${field('position','Position · 岗位')}${field('mission','Mission · 使命',true)}<h3>Required Capabilities</h3>${picker('capabilities',capabilityCatalog)}<label class="hire-field">添加自定义能力<input name="customCapability" placeholder="例如 payments.refund，按 Enter 添加" maxlength="80"></label><h3>Review Capabilities</h3>${picker('review',['code.review','testing','source.review','quality'])}`;
    if(c.step===2)return `<h2>Meet your new employee</h2><p class="hire-muted">身份定义协作方式，职称和个性不会扩大权限。</p><div class="hire-identity"><div>${field('name','Name · 姓名')}<h3>Pixel Avatar</h3><div class="hire-avatars">${Array.from({length:8},(_,i)=>`<button type="button" data-hire-portrait="${i+1}" aria-label="选择头像 ${i+1}" aria-pressed="${c.portrait===i+1}"><img src="/employee/assets/portrait-${i+1}.png" alt=""></button>`).join('')}</div>${field('communication','Communication Style · 沟通风格')}${field('workingStyle','Working Style · 工作方式')}${field('about','About · 简介',true)}</div>${card()}</div>`;
    if(c.step===3)return `<h2>What should ${esc(c.name)} be able to do?</h2><p class="hire-muted">Capability 是会做什么，Skill 是如何开展工作。</p><h3>Capabilities <span class="badge draft">Declared</span></h3>${picker('capabilities',capabilityCatalog)}<h3>Skills · 工作方法</h3><p class="hire-muted">为员工选择可复用的方法包，当前仅演示选择，尚未安装。</p>${picker('skills',skillCatalog)}`;
    if(c.step===4)return `<h2>Access & Authority</h2><p class="hire-principle">Capability ≠ Permission <small>会做，不代表被允许做。</small></p><h3>Knowledge Access</h3>${picker('knowledge',['Engineering Knowledge','Product Docs'])}<p class="hire-muted">选中表示 Read · Finance / Customer Data：No Access</p><h3>Tools / Hands</h3>${picker('tools',['Local Repository','Terminal','Git'])}<p class="hire-muted">GitHub：Requires policy · Shopify / Gmail：No Access</p><h3>Permissions</h3>${picker('permissions',['Read','Draft','Modify workspace'])}<div class="hire-boundaries"><span>Commit <b>Requires policy</b></span><span>External publish <b>禁止</b></span><span>Financial action <b>禁止</b></span></div><details class="hire-advanced"><summary>Advanced → Execution</summary><p>Auto · 系统将在真实执行时选择可用后端。当前未连接执行环境。</p><small>员工身份独立于模型，本次设置不产生真实授权。</small></details>`;
    if(c.step===5)return `<h2>One small task. A confident start.</h2><p class="hire-muted">在 ${esc(c.name)} 加入团队前，先完成一次模拟试用。</p><fieldset ${busy?'disabled':''}>${field('trialTitle','Trial Work · 试用工作')}${field('criteria','Success Criteria · 成功标准',true)}<label class="hire-field">Independent Reviewer · 独立评审员<select name="reviewer"><option value="iris" ${c.reviewer==='iris'?'selected':''}>Iris · Reviewer</option><option value="kai" ${c.reviewer==='kai'?'selected':''}>Kai · Research Analyst</option></select></label><label class="hire-field">演示结果<select id="trial-outcome"><option value="PASS" ${trialOutcome==='PASS'?'selected':''}>通过 PASS</option><option value="REQUEST_REVISION" ${trialOutcome==='REQUEST_REVISION'?'selected':''}>需要修订 REQUEST_REVISION</option></select></label></fieldset><div class="hire-trial-flow"><span data-phase="1">${esc(c.name)}<small>EXECUTION · 模拟</small></span><b>→</b><span data-phase="2">Artifact v1<small>示例交付物</small></span><b>→</b><span data-phase="3">${c.reviewer==='iris'?'Iris':'Kai'}<small>REVIEW · 模拟</small></span></div><div id="trial-progress" role="status">${busy?'正在模拟试用流程…':c.trial?`<strong>${c.trial.verdict==='PASS'?'✓ Trial passed · 模拟通过':'↻ Request revision · 请调整后重试'}</strong><p>Artifact delivered · ${c.trial.verdict==='PASS'?'Verification passed':'成功标准需要补充验证'}</p>${tags(c.capabilities.map(v=>`${v} · observed (demo)`))}`:'能力仍为 Declared；模拟结果不会变为真实 Verified。'}</div><button type="button" class="secondary-button" data-hire-trial ${busy?'disabled':''}>${c.trial?'Adjust & Retry · 重新模拟':'Start Trial · 开始模拟'}</button>`;
    return `<h2>A new teammate, by your decision.</h2><p class="hire-muted">试用通过不代表入职。请确认身份、职责和边界。</p><div class="hire-summary"><div class="hire-summary-person"><img src="/employee/assets/portrait-${c.portrait}.png" alt=""><div><h3>${esc(c.name)}</h3><p>${esc(c.position)}</p></div><span class="badge">Trial PASS · Demo</span></div>${[['Mission',c.mission],['Identity',[c.communication,c.workingStyle,c.about].filter(Boolean).join(' · ')],['Capabilities · Declared',c.capabilities.join(' · ')],['Review capabilities',c.review.join(' · ')],['Skills',c.skills.join(' · ')],['Knowledge · Read',c.knowledge.join(' · ')],['Tools',c.tools.join(' · ')],['Permissions',c.permissions.join(' · ')],['Boundaries','Commit / GitHub 需要策略；禁止外部发布和财务操作'],['Execution','Automatic · 未连接'],['Trial',`${c.trialTitle} / ${c.reviewer==='iris'?'Iris':'Kai'} · 模拟 PASS`],['Success Criteria',c.criteria]].map(([k,v])=>`<div class="hire-summary-row"><strong>${k}</strong><span>${esc(v||'未选择')}</span></div>`).join('')}</div><label class="hire-confirm"><input type="checkbox" id="founder-confirm">我确认上述岗位与权限边界，同意 ${esc(c.name)} 加入本地演示团队。</label>`;
  }
  function render(){dialog.innerHTML=`<header class="hire-sheet-head"><div><span class="eyebrow">HIRING · PROTOTYPE</span><h2 id="hire-title">Hire Employee</h2></div><span>${c.step} of 6</span><button type="button" data-hire-close aria-label="保存草稿并关闭">×</button></header><nav class="hire-steps" aria-label="招聘步骤">${names.map((n,i)=>`<span class="${i+1===c.step?'active':i+1<c.step?'complete':''}" ${i+1===c.step?'aria-current="step"':''}><b>${i+1<c.step?'✓':i+1}</b>${n}</span>`).join('')}</nav><form id="hire-form"><div class="hire-sheet-body">${body()}<p role="alert" class="hire-error"></p></div><footer class="hire-sheet-footer"><button type="button" class="hire-cancel" data-hire-discard>取消招聘</button><span>${store.persistent?'草稿自动保存在本机':'仅本页保存'}</span>${c.step>1?'<button type="button" class="secondary-button" data-hire-back>← Back</button>':''}<button class="primary-button" type="submit" ${busy||c.step===5&&!trialIsCurrent(c)?'disabled':''}>${c.step===6?`Hire ${esc(c.name)}`:'Continue →'}</button></footer></form>`;dialog.querySelector('.hire-sheet-body').scrollTop=0;}
  dialog.addEventListener('input',e=>{
    const el=e.target,key=el.name;if(!key||key==='customCapability')return;
    if(el.type==='checkbox')c[key]=[...dialog.querySelectorAll(`input[name="${key}"]:checked`)].map(x=>x.value);else c[key]=el.value;
    c.trial=null;try{save();}catch(err){error(err.message);}
    const preview=dialog.querySelector('[data-preview-name]');if(key==='name'&&preview)preview.textContent=c.name||'Your new teammate';
    if(c.step===5){dialog.querySelector('#trial-progress').textContent='配置已更新，请重新模拟试用。';dialog.querySelector('[type="submit"]').disabled=true;}
  });
  dialog.addEventListener('keydown',e=>{if(e.target.name==='customCapability'&&e.key==='Enter'){e.preventDefault();const v=e.target.value.trim();if(v&&!c.capabilities.includes(v)){c.capabilities.push(v);c.trial=null;save();render();}}});
  dialog.addEventListener('submit',e=>{e.preventDefault();if(busy)return;const issue=validateStep(c,c.step);if(issue){error(issue);return;}try{
    if(c.step===6){const hire=store.confirm(c,dialog.querySelector('#founder-confirm').checked);onHired(hire);dialog.innerHTML=`<div class="hire-welcome"><span class="eyebrow">YOUR TEAM JUST GREW</span><img src="/employee/assets/portrait-${c.portrait}.png" alt=""><h2 id="hire-title">Welcome, ${esc(c.name)}.</h2><p>${esc(c.name)} joined your company.</p><p class="hire-muted">已加入本地演示团队，等待后续工作。没有触发真实执行。</p>${!store.persistent?'<p class="hire-error">存储不可用：本页可查看员工，跨页后不会保留。</p>':`<a class="primary-button" href="${lobbyURL(hire.employeeId,true)}">View Employee · 前往圆桌 →</a>`}<button class="secondary-button" data-hire-close>Done</button></div>`;return;}
    if(c.step===5&&!trialIsCurrent(c)){error('请先通过模拟试用。');return;}c.step++;save();render();
  }catch(err){error(err.message);}});
  dialog.addEventListener('cancel',()=>{generation++;busy=false;onRefresh();});
  dialog.addEventListener('click',async e=>{const t=e.target.closest('button');if(!t)return;
    if(t.hasAttribute('data-hire-close')){close();return;}
    if(t.hasAttribute('data-hire-discard')){generation++;busy=false;dialog.querySelector('.hire-sheet-body').innerHTML='<h2>取消本次招聘？</h2><p>候选人尚未入职。删除草稿后，你仍可从岗位模板重新开始。</p><button type="button" class="secondary-button" data-hire-keep>继续编辑</button> <button type="button" class="primary-button" data-hire-delete>删除招聘草稿</button>';dialog.querySelector('.hire-sheet-footer').hidden=true;return;}
    if(t.hasAttribute('data-hire-keep')){render();return;}
    if(t.hasAttribute('data-hire-delete')){store.discard(c.id);close();return;}
    if(t.hasAttribute('data-hire-back')){generation++;busy=false;c.step--;save();render();return;}
    if(t.dataset.hirePortrait){c.portrait=Number(t.dataset.hirePortrait);c.trial=null;save();render();return;}
    if(t.hasAttribute('data-hire-trial')){const issue=validateStep(c,5);if(issue){error(issue);return;}const verdict=dialog.querySelector('#trial-outcome').value;trialOutcome=verdict;c.trial=null;save();busy=true;const token=++generation;render();for(let phase=1;phase<=3;phase++){if(token!==generation||!dialog.open)return;dialog.querySelector(`[data-phase="${phase}"]`).classList.add('active');dialog.querySelector('#trial-progress').textContent=['','正在模拟执行…','示例交付物已生成…','独立评审进行中…'][phase];await new Promise(resolve=>setTimeout(resolve,650));}if(token!==generation||!dialog.open)return;busy=false;c.trial={source:'demo',verdict,fingerprint:candidateFingerprint(c),at:new Date().toISOString()};save();render();}
  });
  document.addEventListener('click',e=>{const t=e.target.closest('[data-hire-new],[data-hire-need],[data-hire-resume]');if(!t)return;if(t.hasAttribute('data-hire-need'))open('engineer','payments.integration');else if(t.dataset.hireResume)open('engineer','',store.drafts.find(d=>d.id===t.dataset.hireResume));else open(t.dataset.hireNew);});
  return {overview};
}
